# Generated by Django 4.1.3 on 2022-11-09 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='document_name',
        ),
        migrations.RemoveField(
            model_name='register',
            name='is_registered',
        ),
        migrations.RemoveField(
            model_name='student',
            name='document',
        ),
        migrations.AddField(
            model_name='register',
            name='department_name',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Computer Systems Engineering', 'Computer Systems Engineering'), ('Informatics', 'Informatics'), ('Information Technology', 'Information Technology')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='register',
            name='document',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='register',
            name='student_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
    ]
