# Generated by Django 4.1.2 on 2022-11-16 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=200)),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Computer Systems Engineering', 'Computer Systems Engineering'), ('Informatics', 'Informatics'), ('Information Technology', 'Information Technology')], default='', max_length=100)),
                ('uploaded_file', models.FileField(default='', upload_to='')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
